name: getGR

on:
  schedule:
    - cron: '30 16 * * *'  # Runs at 16:30 UTC, which is 10:00 PM IST

  push:
    branches: [ main ]


jobs:
  fetch_site:
    runs-on: ubuntu-latest
    outputs:
      commit_hash: ${{ steps.commit-and-push.outputs.commit_hash }}

    steps:
      - name: checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "0.5.16"

      - name: "Set up Python"
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: make install

      - name: Install chromium
        run: make install_chromium

      - name: Fetch website
        run: make fetch_site

      - name: Merge the fetched pages
        run: make merge_fetch

      - name: Commit and push Changes
        id: commit-and-push
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: After merge_fetch

  link_wayback:
    runs-on: ubuntu-latest
    needs: fetch_site
    outputs:
      commit_hash: ${{ steps.commit-and-push.outputs.commit_hash }}

    steps:
      - name: checkout code
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "0.5.16"

      - name: "Set up Python"
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: make install

      - name: Link to wayback machine
        run: make link_wayback

      - name: Pull changes in the repository
        run: |
          git pull

      - name: Commit and Push Changes
        id: commit-and-push
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: After link_wayback


  upload_to_archive:
    runs-on: ubuntu-latest
    needs: link_wayback
    outputs:
      commit_hash: ${{ steps.commit-and-push.outputs.commit_hash }}

    steps:
      - name: checkout code
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "0.5.16"

      - name: "Set up Python"
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'


      - name: Install dependencies
        run: make install

      - name: Upload to archive
        env:
          IA_ACCESS_KEY: ${{ secrets.IA_ACCESS_KEY }}
          IA_SECRET_KEY: ${{ secrets.IA_SECRET_KEY }}

        run: make upload_to_archive

      - name: Pull changes in the repository
        run: |
          git pull

      - name: Commit and Push Changes
        id: commit-and-push
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Uploaded to archive


  export:
    runs-on: ubuntu-latest
    needs: upload_to_archive
    outputs:
      commit_hash: ${{ steps.commit-and-push.outputs.commit_hash }}

    steps:
      - name: checkout code
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "0.5.16"

      - name: "Set up Python"
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: make install

      - name: export
        run: make export

      - name: Pull changes in the repository
        run: |
          git pull

      - name: Commit and Push Changes
        id: commit-and-push
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: exported
